"""初始迁移：一次性建立 SPEC §2 全部实体与枚举

数据库级不变量（后续迁移只能增量扩展，不得重设实体归属）：
- parse_task.quote_id ON DELETE SET NULL：报价删除后任务与 rawResult 保留可回放；
- quote_file_link / parse_task_file 联合主键：文件可被多报价共享、任务输入固定；
- field_evidence (quote_id, field_name) 唯一：标量字段证据不漂移；
- 各金额列非负 CheckConstraint：null 不当 0，但绝不出现负金额；
- uq_parse_task_active_quote 部分唯一索引：同一报价最多一个活动解析任务（互斥）。

Revision ID: 0001
Revises:
Create Date: 2026-08-26 15:39:21.273468

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# 本迁移创建的全部原生枚举类型。
# PostgreSQL 的 DROP TABLE 不会回收 ENUM 类型，downgrade 必须显式清理，
# 否则“降级后再升级”会因类型已存在而失败（已由测试覆盖）。
_ENUM_TYPES = (
    'quote_source',
    'quote_status',
    'price_item_status',
    'official_total_status',
    'total_check_status',
    'net_payment_status',
    'coverage_category',
    'item_status',
    'confidence_level',
    'service_type',
    'package_unit',
    'annotation_kind',
    'annotation_source_type',
    'discount_type',
    'parse_task_status',
    'merge_change_kind',
    'merge_resolution',
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comparison_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('renewal_year', sa.Integer(), nullable=False),
    sa.Column('expire_date', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('vehicle_name', sa.Text(), nullable=False),
    sa.Column('vehicle_model', sa.Text(), nullable=True),
    sa.Column('vehicle_seats', sa.Integer(), nullable=True),
    sa.Column('first_reg_date', sa.Text(), nullable=True),
    sa.Column('is_nev', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('model_consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('renewal_year BETWEEN 2000 AND 2100', name=op.f('ck_comparison_project_renewal_year_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comparison_project'))
    )
    op.create_index('ix_comparison_project_created_at', 'comparison_project', ['created_at'], unique=False)
    op.create_table('quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('insurer_code', sa.Text(), nullable=False),
    sa.Column('insurer_name', sa.Text(), nullable=False),
    sa.Column('agent_name', sa.Text(), nullable=True),
    sa.Column('plan_label', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('UPLOADED', 'MANUAL', name='quote_source'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PARSING', 'PENDING_CONFIRM', 'CONFIRMED', 'PARSE_FAILED', 'MERGE_REVIEW', name='quote_status'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('version_group_id', sa.Uuid(), nullable=True),
    sa.Column('vehicle_model', sa.Text(), nullable=True),
    sa.Column('vehicle_seats', sa.Integer(), nullable=True),
    sa.Column('first_reg_date', sa.Text(), nullable=True),
    sa.Column('is_nev', sa.Boolean(), nullable=True),
    sa.Column('commercial_premium', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('computed_commercial_premium', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('compulsory_premium', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('vehicle_tax', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('package_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('computed_package_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('other_fees', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('commercial_status', sa.Enum('INCLUDED', 'NOT_INCLUDED', 'UNKNOWN', name='price_item_status'), nullable=False),
    sa.Column('compulsory_status', sa.Enum('INCLUDED', 'NOT_INCLUDED', 'UNKNOWN', name='price_item_status'), nullable=False),
    sa.Column('vehicle_tax_status', sa.Enum('INCLUDED', 'NOT_INCLUDED', 'UNKNOWN', name='price_item_status'), nullable=False),
    sa.Column('package_status', sa.Enum('INCLUDED', 'NOT_INCLUDED', 'UNKNOWN', name='price_item_status'), nullable=False),
    sa.Column('other_fees_status', sa.Enum('INCLUDED', 'NOT_INCLUDED', 'UNKNOWN', name='price_item_status'), nullable=False),
    sa.Column('official_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('official_total_status', sa.Enum('INCLUDED', 'UNKNOWN', name='official_total_status'), nullable=False),
    sa.Column('computed_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_check_status', sa.Enum('NOT_CHECKABLE', 'PASSED', 'MISMATCH', name='total_check_status'), nullable=False),
    sa.Column('net_payment', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('net_payment_status', sa.Enum('OK', 'MISSING_TOTAL', 'INVALID_DISCOUNT', name='net_payment_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('commercial_premium IS NULL OR commercial_premium >= 0', name=op.f('ck_quote_commercial_premium_non_negative')),
    sa.CheckConstraint('compulsory_premium IS NULL OR compulsory_premium >= 0', name=op.f('ck_quote_compulsory_premium_non_negative')),
    sa.CheckConstraint('computed_commercial_premium IS NULL OR computed_commercial_premium >= 0', name=op.f('ck_quote_computed_commercial_premium_non_negative')),
    sa.CheckConstraint('computed_package_total IS NULL OR computed_package_total >= 0', name=op.f('ck_quote_computed_package_total_non_negative')),
    sa.CheckConstraint('computed_total IS NULL OR computed_total >= 0', name=op.f('ck_quote_computed_total_non_negative')),
    sa.CheckConstraint('net_payment IS NULL OR net_payment >= 0', name=op.f('ck_quote_net_payment_non_negative')),
    sa.CheckConstraint('official_total IS NULL OR official_total >= 0', name=op.f('ck_quote_official_total_non_negative')),
    sa.CheckConstraint('other_fees IS NULL OR other_fees >= 0', name=op.f('ck_quote_other_fees_non_negative')),
    sa.CheckConstraint('package_total IS NULL OR package_total >= 0', name=op.f('ck_quote_package_total_non_negative')),
    sa.CheckConstraint('vehicle_seats IS NULL OR vehicle_seats > 0', name=op.f('ck_quote_vehicle_seats_positive')),
    sa.CheckConstraint('vehicle_tax IS NULL OR vehicle_tax >= 0', name=op.f('ck_quote_vehicle_tax_non_negative')),
    sa.ForeignKeyConstraint(['project_id'], ['comparison_project.id'], name=op.f('fk_quote_project_id_comparison_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quote'))
    )
    op.create_index('ix_quote_project_id', 'quote', ['project_id'], unique=False)
    op.create_index('ix_quote_status', 'quote', ['status'], unique=False)
    op.create_table('quote_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('original_name', sa.Text(), nullable=False),
    sa.Column('mime', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('page_count >= 1', name=op.f('ck_quote_file_page_count_positive')),
    sa.CheckConstraint('size_bytes >= 0', name=op.f('ck_quote_file_size_bytes_non_negative')),
    sa.ForeignKeyConstraint(['project_id'], ['comparison_project.id'], name=op.f('fk_quote_file_project_id_comparison_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quote_file'))
    )
    op.create_index('ix_quote_file_project_id', 'quote_file', ['project_id'], unique=False)
    op.create_table('discount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('discount_type', sa.Enum('CASH', 'RED_PACKET', 'GIFT_CARD', 'OIL_CARD', 'COUPON', 'SERVICE', 'OTHER', name='discount_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cash_equivalent', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('include_in_net', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount IS NULL OR amount >= 0', name=op.f('ck_discount_amount_non_negative')),
    sa.CheckConstraint('cash_equivalent IS NULL OR cash_equivalent >= 0', name=op.f('ck_discount_cash_equivalent_non_negative')),
    sa.ForeignKeyConstraint(['quote_id'], ['quote.id'], name=op.f('fk_discount_quote_id_quote'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discount'))
    )
    op.create_index('ix_discount_quote_id', 'discount', ['quote_id'], unique=False)
    op.create_table('field_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.Text(), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('confidence_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidence_level'), nullable=False),
    sa.Column('edited_by_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('source_page IS NULL OR source_page >= 1', name=op.f('ck_field_evidence_source_page_positive')),
    sa.ForeignKeyConstraint(['quote_id'], ['quote.id'], name=op.f('fk_field_evidence_quote_id_quote'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['quote_file.id'], name=op.f('fk_field_evidence_source_file_id_quote_file'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_field_evidence')),
    sa.UniqueConstraint('quote_id', 'field_name', name='uq_field_evidence_quote_field')
    )
    op.create_index('ix_field_evidence_quote_id', 'field_evidence', ['quote_id'], unique=False)
    op.create_table('parse_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', name='parse_task_status'), nullable=False),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('raw_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempt >= 0', name=op.f('ck_parse_task_attempt_non_negative')),
    sa.ForeignKeyConstraint(['project_id'], ['comparison_project.id'], name=op.f('fk_parse_task_project_id_comparison_project'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quote_id'], ['quote.id'], name=op.f('fk_parse_task_quote_id_quote'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parse_task'))
    )
    op.create_index('ix_parse_task_quote_id', 'parse_task', ['quote_id'], unique=False)
    op.create_index('ix_parse_task_status', 'parse_task', ['status'], unique=False)
    op.create_index('uq_parse_task_active_quote', 'parse_task', ['quote_id'], unique=True, postgresql_where=sa.text("status IN ('PENDING', 'RUNNING') AND quote_id IS NOT NULL"))
    op.create_table('quote_coverage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('CORE', 'ADDITIONAL', 'UNRECOGNIZED', name='coverage_category'), nullable=False),
    sa.Column('raw_name', sa.Text(), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('INCLUDED', 'NOT_INCLUDED', 'FREE', 'NOT_APPLICABLE', 'UNKNOWN', name='item_status'), nullable=False),
    sa.Column('coverage_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('per_seat_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('seat_count', sa.Integer(), nullable=True),
    sa.Column('shared_coverage', sa.Boolean(), nullable=True),
    sa.Column('premium', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('multiplier', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('confidence_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidence_level'), nullable=False),
    sa.Column('edited_by_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category <> 'UNRECOGNIZED' OR code IS NULL", name=op.f('ck_quote_coverage_unrecognized_has_no_code')),
    sa.CheckConstraint('coverage_amount IS NULL OR coverage_amount >= 0', name=op.f('ck_quote_coverage_coverage_amount_non_negative')),
    sa.CheckConstraint('multiplier IS NULL OR multiplier >= 0', name=op.f('ck_quote_coverage_multiplier_non_negative')),
    sa.CheckConstraint('per_seat_amount IS NULL OR per_seat_amount >= 0', name=op.f('ck_quote_coverage_per_seat_amount_non_negative')),
    sa.CheckConstraint('premium IS NULL OR premium >= 0', name=op.f('ck_quote_coverage_premium_non_negative')),
    sa.CheckConstraint('seat_count IS NULL OR seat_count > 0', name=op.f('ck_quote_coverage_seat_count_positive')),
    sa.ForeignKeyConstraint(['quote_id'], ['quote.id'], name=op.f('fk_quote_coverage_quote_id_quote'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['quote_file.id'], name=op.f('fk_quote_coverage_source_file_id_quote_file'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quote_coverage'))
    )
    op.create_index('ix_quote_coverage_code', 'quote_coverage', ['code'], unique=False)
    op.create_index('ix_quote_coverage_quote_id', 'quote_coverage', ['quote_id'], unique=False)
    op.create_table('quote_file_link',
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['quote_file.id'], name=op.f('fk_quote_file_link_file_id_quote_file'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quote_id'], ['quote.id'], name=op.f('fk_quote_file_link_quote_id_quote'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quote_id', 'file_id', name='pk_quote_file_link')
    )
    op.create_table('quote_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.Enum('ROAD_RESCUE', 'INSPECTION', 'DRIVER_SERVICE', 'INSPECTION_AGENT', 'OTHER', name='service_type'), nullable=False),
    sa.Column('status', sa.Enum('INCLUDED', 'NOT_INCLUDED', 'FREE', 'NOT_APPLICABLE', 'UNKNOWN', name='item_status'), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('raw_name', sa.Text(), nullable=True),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('confidence_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidence_level'), nullable=False),
    sa.Column('edited_by_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cost IS NULL OR cost >= 0', name=op.f('ck_quote_service_cost_non_negative')),
    sa.CheckConstraint('count IS NULL OR count >= 0', name=op.f('ck_quote_service_count_non_negative')),
    sa.ForeignKeyConstraint(['quote_id'], ['quote.id'], name=op.f('fk_quote_service_quote_id_quote'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['quote_file.id'], name=op.f('fk_quote_service_source_file_id_quote_file'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quote_service'))
    )
    op.create_index('ix_quote_service_quote_id', 'quote_service', ['quote_id'], unique=False)
    op.create_table('sales_annotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('kind', sa.Enum('RED_TEXT', 'ARROW', 'HANDWRITTEN', 'EXTRA_PROMO', 'OTHER', name='annotation_kind'), nullable=False),
    sa.Column('source_type', sa.Enum('SALES_ANNOTATION', 'USER_ANNOTATION', name='annotation_source_type'), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('edited_by_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quote.id'], name=op.f('fk_sales_annotation_quote_id_quote'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['quote_file.id'], name=op.f('fk_sales_annotation_source_file_id_quote_file'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_annotation'))
    )
    op.create_index('ix_sales_annotation_quote_id', 'sales_annotation', ['quote_id'], unique=False)
    op.create_table('supplemental_package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('raw_name', sa.Text(), nullable=True),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('premium', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('confidence_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidence_level'), nullable=False),
    sa.Column('edited_by_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('premium IS NULL OR premium >= 0', name=op.f('ck_supplemental_package_premium_non_negative')),
    sa.ForeignKeyConstraint(['quote_id'], ['quote.id'], name=op.f('fk_supplemental_package_quote_id_quote'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['quote_file.id'], name=op.f('fk_supplemental_package_source_file_id_quote_file'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplemental_package'))
    )
    op.create_index('ix_supplemental_package_quote_id', 'supplemental_package', ['quote_id'], unique=False)
    op.create_table('merge_change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('parse_task_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_key', sa.Text(), nullable=False),
    sa.Column('field_name', sa.Text(), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('kind', sa.Enum('ADD', 'CONFLICT', name='merge_change_kind'), nullable=False),
    sa.Column('resolution', sa.Enum('ACCEPT', 'KEEP', 'PENDING', name='merge_resolution'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parse_task_id'], ['parse_task.id'], name=op.f('fk_merge_change_parse_task_id_parse_task'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quote_id'], ['quote.id'], name=op.f('fk_merge_change_quote_id_quote'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merge_change'))
    )
    op.create_index('ix_merge_change_parse_task_id', 'merge_change', ['parse_task_id'], unique=False)
    op.create_index('ix_merge_change_quote_id', 'merge_change', ['quote_id'], unique=False)
    op.create_table('package_coverage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('INCLUDED', 'NOT_INCLUDED', 'FREE', 'NOT_APPLICABLE', 'UNKNOWN', name='item_status'), nullable=False),
    sa.Column('coverage_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('unit', sa.Enum('CNY', 'TIMES', 'DAYS', 'OTHER', name='package_unit'), nullable=True),
    sa.Column('per_seat_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('seat_count', sa.Integer(), nullable=True),
    sa.Column('shared', sa.Boolean(), nullable=True),
    sa.Column('multiplier', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('confidence_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidence_level'), nullable=False),
    sa.Column('edited_by_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('coverage_amount IS NULL OR coverage_amount >= 0', name=op.f('ck_package_coverage_coverage_amount_non_negative')),
    sa.CheckConstraint('multiplier IS NULL OR multiplier >= 0', name=op.f('ck_package_coverage_multiplier_non_negative')),
    sa.CheckConstraint('per_seat_amount IS NULL OR per_seat_amount >= 0', name=op.f('ck_package_coverage_per_seat_amount_non_negative')),
    sa.CheckConstraint('seat_count IS NULL OR seat_count > 0', name=op.f('ck_package_coverage_seat_count_positive')),
    sa.ForeignKeyConstraint(['package_id'], ['supplemental_package.id'], name=op.f('fk_package_coverage_package_id_supplemental_package'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['quote_file.id'], name=op.f('fk_package_coverage_source_file_id_quote_file'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_coverage'))
    )
    op.create_index('ix_package_coverage_package_id', 'package_coverage', ['package_id'], unique=False)
    op.create_table('parse_task_file',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('input_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['quote_file.id'], name=op.f('fk_parse_task_file_file_id_quote_file'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['parse_task.id'], name=op.f('fk_parse_task_file_task_id_parse_task'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'file_id', name='pk_parse_task_file')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parse_task_file')
    op.drop_index('ix_package_coverage_package_id', table_name='package_coverage')
    op.drop_table('package_coverage')
    op.drop_index('ix_merge_change_quote_id', table_name='merge_change')
    op.drop_index('ix_merge_change_parse_task_id', table_name='merge_change')
    op.drop_table('merge_change')
    op.drop_index('ix_supplemental_package_quote_id', table_name='supplemental_package')
    op.drop_table('supplemental_package')
    op.drop_index('ix_sales_annotation_quote_id', table_name='sales_annotation')
    op.drop_table('sales_annotation')
    op.drop_index('ix_quote_service_quote_id', table_name='quote_service')
    op.drop_table('quote_service')
    op.drop_table('quote_file_link')
    op.drop_index('ix_quote_coverage_quote_id', table_name='quote_coverage')
    op.drop_index('ix_quote_coverage_code', table_name='quote_coverage')
    op.drop_table('quote_coverage')
    op.drop_index('uq_parse_task_active_quote', table_name='parse_task', postgresql_where=sa.text("status IN ('PENDING', 'RUNNING') AND quote_id IS NOT NULL"))
    op.drop_index('ix_parse_task_status', table_name='parse_task')
    op.drop_index('ix_parse_task_quote_id', table_name='parse_task')
    op.drop_table('parse_task')
    op.drop_index('ix_field_evidence_quote_id', table_name='field_evidence')
    op.drop_table('field_evidence')
    op.drop_index('ix_discount_quote_id', table_name='discount')
    op.drop_table('discount')
    op.drop_index('ix_quote_file_project_id', table_name='quote_file')
    op.drop_table('quote_file')
    op.drop_index('ix_quote_status', table_name='quote')
    op.drop_index('ix_quote_project_id', table_name='quote')
    op.drop_table('quote')
    op.drop_index('ix_comparison_project_created_at', table_name='comparison_project')
    op.drop_table('comparison_project')
    # ### end Alembic commands ###
    # 回收全部枚举类型，保证降级后数据库真正回到空库、可再次升级
    for enum_name in _ENUM_TYPES:
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
