/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description 存活探针；不触碰数据库，供容器/脚本判断服务是否起来。
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Projects
         * @description 项目列表（含报价数与最低有效净支出聚合；无报价时为稳定空列表）。
         */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        /**
         * Create Project
         * @description 创建续保对比项目。
         */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Project
         * @description 项目详情。
         */
        get: operations["get_project_api_projects__project_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Project
         * @description 删除项目（不可恢复）：级联删除报价与文件记录，并预约磁盘清理。
         */
        delete: operations["delete_project_api_projects__project_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Project
         * @description 编辑项目基础信息。
         */
        patch: operations["update_project_api_projects__project_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiResponse[HealthData] */
        ApiResponse_HealthData_: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            data?: components["schemas"]["HealthData"] | null;
        };
        /** ApiResponse[NoneType] */
        ApiResponse_NoneType_: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Data */
            data?: null;
        };
        /** ApiResponse[ProjectRead] */
        ApiResponse_ProjectRead_: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            data?: components["schemas"]["ProjectRead"] | null;
        };
        /** ApiResponse[list[ProjectListItem]] */
        ApiResponse_list_ProjectListItem__: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Data */
            data?: components["schemas"]["ProjectListItem"][] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthData */
        HealthData: {
            /** Status */
            status: string;
        };
        /**
         * ProjectCreate
         * @description 创建项目：字段严格限定为项目名、车辆名称、续保年份、可选到期日与备注。
         */
        ProjectCreate: {
            /**
             * Name
             * @description 项目名称，如“2026 车辆续保”
             */
            name: string;
            /**
             * Vehiclename
             * @description 车辆名称，如 Model Y
             */
            vehicleName: string;
            /**
             * Renewalyear
             * @description 续保年份
             */
            renewalYear: number;
            /**
             * Expiredate
             * @description 保险到期时间（可选）
             */
            expireDate?: string | null;
            /**
             * Note
             * @description 备注（可选，入库前脱敏）
             */
            note?: string | null;
        };
        /**
         * ProjectListItem
         * @description 项目列表项：附带报价数与最低有效净支出聚合。
         *
         *     “有效净支出”只统计已确认（CONFIRMED/MERGE_REVIEW）且 netPayment 非空的报价；
         *     无有效报价时 minNetPayment 为 null（稳定空状态，前端不得当作 0 处理）。
         */
        ProjectListItem: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Vehiclename */
            vehicleName: string;
            /** Renewalyear */
            renewalYear: number;
            /** Expiredate */
            expireDate?: string | null;
            /** Note */
            note?: string | null;
            /** Vehiclemodel */
            vehicleModel?: string | null;
            /** Vehicleseats */
            vehicleSeats?: number | null;
            /** Firstregdate */
            firstRegDate?: string | null;
            /** Isnev */
            isNev?: boolean | null;
            /** Modelconsentat */
            modelConsentAt?: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /** Quotecount */
            quoteCount: number;
            /** Minnetpayment */
            minNetPayment?: number | null;
        };
        /**
         * ProjectRead
         * @description 项目详情（含车辆摘要字段；摘要由首份确认报价回填，当前 MVP 阶段为空）。
         */
        ProjectRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Vehiclename */
            vehicleName: string;
            /** Renewalyear */
            renewalYear: number;
            /** Expiredate */
            expireDate?: string | null;
            /** Note */
            note?: string | null;
            /** Vehiclemodel */
            vehicleModel?: string | null;
            /** Vehicleseats */
            vehicleSeats?: number | null;
            /** Firstregdate */
            firstRegDate?: string | null;
            /** Isnev */
            isNev?: boolean | null;
            /** Modelconsentat */
            modelConsentAt?: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /**
         * ProjectUpdate
         * @description 编辑项目：全部字段可选，仅更新显式提供的字段（PATCH 语义）。
         */
        ProjectUpdate: {
            /** Name */
            name?: string | null;
            /** Vehiclename */
            vehicleName?: string | null;
            /** Renewalyear */
            renewalYear?: number | null;
            /** Expiredate */
            expireDate?: string | null;
            /** Note */
            note?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_HealthData_"];
                };
            };
        };
    };
    list_projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_ProjectListItem__"];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ProjectRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ProjectRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_api_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ProjectRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
